name: xAI-FL-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.17
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - pytorch-lightning=2.4.0
  - torchvision=0.19.0
  - tensorboard>=2.4.1
  - numpy=1.26.4 
  - scipy=1.14.1
  - scikit-learn=1.5.1
  - matplotlib >= 3.9.2
  - faiss-gpu=1.8.0
  - tqdm>=4.66.5
  - timm>=1.0.9
  - torchinfo=1.8.0
  - opacus
  - pip:
    - medmnist==3.0.2
    - wilds
    - geomloss
    - chromadb

